# Generated by Django 2.0 on 2017-12-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171219_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Stops',
            field=models.BigIntegerField(max_length=250),
        ),
    ]
