# Generated by Django 2.0 on 2017-12-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171219_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Destination_airport_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Aeropuerto'),
        ),
        migrations.AlterField(
            model_name='route',
            name='Stops',
            field=models.BigIntegerField(max_length=250),
        ),
    ]
