# Generated by Django 2.0 on 2017-12-20 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_route_destination_airport_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stops', models.BigIntegerField()),
                ('Airline_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Aerolinea')),
                ('Destination_airport_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Aeropuerto')),
                ('Source_airport_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SRC', to='polls.Aeropuerto')),
            ],
        ),
    ]
