# Generated by Django 2.0 on 2017-12-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rutas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rutas',
            new_name='Ruta',
        ),
        migrations.RemoveField(
            model_name='route',
            name='Airline_ID',
        ),
        migrations.RemoveField(
            model_name='route',
            name='Source_airport_ID',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
