# Generated by Django 2.0 on 2017-12-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20171219_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='Destination_airport_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Aeropuerto'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='Source_airport_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SRC', to='polls.Aeropuerto'),
        ),
    ]
