# Generated by Django 2.0 on 2017-12-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_paises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paises',
            new_name='Pais',
        ),
    ]
