# Generated by Django 2.0 on 2017-12-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20171225_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
