# Generated by Django 2.0 on 2018-01-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_delete_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=250)),
                ('celular', models.IntegerField(default=0)),
                ('f_partida', models.DateTimeField()),
                ('f_retorno', models.DateTimeField()),
                ('ciudad_partida', models.CharField(max_length=100)),
                ('ciudad_llegada', models.CharField(max_length=100)),
                ('escala', models.BooleanField(default=True)),
            ],
        ),
    ]
