# Generated by Django 2.0 on 2018-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='f_partida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='f_retorno',
            field=models.DateField(),
        ),
    ]
